AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - "storage/**/*"
    - "tmp/**/*"
    - "db/seeds.rb"
    - "node_modules/**/*"

Layout/TrailingEmptyLines:
  Enabled: true
  AutoCorrect: true
  EnforcedStyle: final_newline

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
  EnforcedStyle: new_line

Layout/RescueEnsureAlignment:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
